## Numpy array and basics


In [2]:
import numpy as np

creating array from list


In [3]:
arr_1D=np.array([1,2,3,4,5])
print("1D array:", arr_1D)
arr_2D=np.array([[1,2,3],[4,5,6]])
print("2D array:\n", arr_2D)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


List vs numpy array


In [ ]:
py_list=[1,2,3] #ELEMENTS wise multiplication
print("Python List:", py_list *2)
np_array=np.array([1,2,3]) #ELEMENTS wise multiplication    
print("NumPy Array:", np_array *2)

Python List: [1, 2, 3, 1, 2, 3]
NumPy Array: [2 4 6]


In [8]:
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("Python list time:", time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("NumPy array time:", time.time()-start)

Python list time: 0.23090004920959473
NumPy array time: 0.011575937271118164


creating array from scratch


In [15]:
zeros=np.zeros((2,3))
print("Zeros array:\n", zeros)

ones=np.ones((2,3))
print("Ones array:\n", ones)

full=np.full((2,3),7)
print("Full array:\n", full)

eye=np.eye(3)
print("Identity matrix:\n", eye)

rand=np.random.random((2,3))
print("Random array:\n", rand)

sequence=np.arange(0,11,2)
print("Sequence array:", sequence)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array:
 [[7 7 7]
 [7 7 7]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
 [[0.69908765 0.89767936 0.93477839]
 [0.60987924 0.69129631 0.55263113]]
Sequence array: [ 0  2  4  6  8 10]


Vector, Matrix and Tensor


In [18]:
vector=np.array([1,2,3])
print("Vector", vector)

matrix=np.array([[1,2,3]
                ,[4,5,6]
               ,[7,8,9]])
print("Matrix:\n", matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor:\n", tensor)

Vector [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties


In [ ]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("Array shape:", arr.shape)
print("Array dimensions:", arr.ndim)
print("Array size (number of elements):", arr.size)
print("Array data type:", arr.dtype)

Array shape: (2, 5)
Array dimensions: 2
Array size: 10
Array data type: int64


### Array Reshaping


In [25]:
arr=np.arange(12)
print("Original array:", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array (3x4):\n", reshaped)

flattened = reshaped.flatten()
print("Flattened array:", flattened)

# Flattened array creates a copy, while ravel creates a view (no copy)
raveled = reshaped.ravel()
print("Raveled array:", raveled)

transposed = reshaped.T
print("Transposed array:\n", transposed)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
